name: booking-lapangan
services:
  payment-service:
    container_name: payment-service
    platform: linux/amd64
    image: bangbintang/payment-service:2
    ports:
      - "8003:8003"
    env_file:
      - .env
